added change-information, change-password endpoints. refactored manua…
KyoshiNoda/Steam-Time pull request #56
Opened 2024-03-13 21:25 UTC by Dylannandlall

added change-information, change-password endpoints. refactored manual_register function in auth.py. Created new login function for manual login within auth.py. Added update_user, find_user_by_email, and verify_password database functions within util.py

2024-03-15 16:22 UTC, KyoshiNoda requested changes
looks really good! 🐐

Requested 3 changes, the rest are optionals/suggestions.

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/routes/auth.py
> +            return Response("Login Failed", status=401, mimetype='application/json')
**_MANDATORY:_**
- Throw errors for each condition. 
- At the end, send a Response OK

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/routes/users.py
> +    """
remove comments

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/routes/users.py
> +    """
remove comments

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/routes/auth.py
> +from database.util import find_user_by_email, verify_password
consider doing `*` for all future imports
```suggestion
from database.util import *
```

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/database/util.py
> +    return bool(user)
**_MANDATORY:_** return the `user.to_dict()`
```suggestion
return user.to_dict() if user else None
```

2024-03-15 16:22 UTC, KyoshiNoda commented on backend/database/util.py
> +        return False
**_MANDATORY:_**
I rather send the user itself everytime we update. I got it working on my branch. Could you just use the following instead? I have test already.
```suggestion
def update_user(steam_id, new_fields):
    try:
        user = User.query.filter_by(steam_id=steam_id).first()
        if user:
            for key, value in new_fields.items():
                setattr(user, key, value)
            db.session.commit()
            return user.to_dict()
        else:
            return None
    except Exception as e:
        db.session.rollback()
        return e
```

2024-03-18 23:45 UTC, Dylannandlall reviewed
looks good

2024-03-19 04:19 UTC, Dylannandlall reviewed
changes made, inform if they are acceptable.

2024-03-19 04:22 UTC, KyoshiNoda approved these changes

2024-03-19 14:58 UTC, merged